
#ifndef FLIF_WINDOWS_PLUGIN_VERSION_H
#define FLIF_WINDOWS_PLUGIN_VERSION_H


#define PRODUCT_NAME "FLIF Windows Plugin"
#define INTERNAL_NAME "flif_windows_plugin.dll"

#define PROJECT_MAJOR_VERSION 1
#define PROJECT_MINOR_VERSION 1
#define PROJECT_PATCH_VERSION 0

#define TO_STR_HELPER(x) #x
#define TO_STR(x) TO_STR_HELPER(x)

#endif  /* FLIF_WINDOWS_PLUGIN_VERSION_H */
